(() => {
  'use strict';
  const M=window.InfinityModel, key=(a,b)=>a<b?`${a}:${b}`:`${b}:${a}`;
  function mount(container,initial='center'){
    const root=document.createElement('div');root.className='ci-widget';container.append(root);
    const dialog=container.closest('dialog');dialog?.classList.add('ci-dialog');if(dialog)dialog.querySelector('#widget-title').textContent='Center of Infinity';
    root.innerHTML=`<div class="ci-tabs" role="tablist" aria-label="Center of Infinity lessons"><button data-ci="center" role="tab">1 · Find the center</button><button data-ci="layers" role="tab">2 · Match layers</button><button data-ci="arms" role="tab">3 · Four arms</button><button data-ci="full" role="tab">4 · Full solution</button><button data-ci="game" role="tab">Map detective</button></div>
      <p class="ci-intro" data-ci="intro"></p>
      <div class="ci-setup"><label>Stations per ring N<select data-ci="n">${[4,6,8,10,12].map(n=>`<option ${n===6?'selected':''}>${n}</option>`).join('')}</select></label><label>Example<select data-ci="example"><option value="book">Book · N = 6</option><option value="random">Shuffled IDs</option></select></label><button data-ci="shuffle">New labels</button><label data-ci="anchor-label">Anchor A<select data-ci="anchor"></select></label><label data-ci="case-label">Anchor case<select data-ci="case"><option value="ordinary">Away from center / antipode</option><option value="center">Center</option><option value="opposite">Antipode</option></select></label><label data-ci="budget-label" hidden>Game budget<select data-ci="budget"><option value="limited">4N + 6</option><option value="practice">Unlimited practice</option></select></label></div>
      <div class="ci-playback" data-ci="playback"><button data-ci="reset" aria-label="Restart lesson">↺</button><button data-ci="back" aria-label="Previous step">←</button><button data-ci="step" class="ci-primary">Step →</button><button data-ci="play">▶ Play</button><button data-ci="finish">Finish</button><select data-ci="speed" aria-label="Animation speed"><option value="1000">Slow</option><option value="500" selected>Normal</option><option value="100">Fast</option></select><span data-ci="progress"></span></div>
      <p class="ci-status" data-ci="status" role="status" aria-live="polite"></p>
      <div class="ci-workspace"><section class="ci-map-pane"><div class="ci-heading"><h3 data-ci="map-title">Recover the station IDs</h3><span data-ci="matched"></span></div>
        <div class="ci-map-tools"><button data-ci="flip-left">Reverse green ring</button><button data-ci="flip-right">Reverse purple ring</button><button data-ci="swap-rings">Swap rings</button><span data-ci="orientation">Orientation 1 / 8</span><button data-ci="map-out" aria-label="Zoom map out">−</button><button data-ci="map-in" aria-label="Zoom map in">+</button></div>
        <div class="ci-map-scroll" data-ci="map-scroll"><svg data-ci="map" viewBox="0 0 700 350" aria-label="Green and purple railway lines; unassigned stations have question marks"></svg></div>
        <div class="ci-map-key"><span><i class="ci-green"></i> Green ring</span><span><i class="ci-purple"></i> Purple ring</span><span><i class="ci-gold"></i> Queried / selected</span><span>? = not recovered</span></div><div data-ci="lesson-pool"></div><div data-ci="game-pool"></div>
        <div class="ci-game-actions" data-ci="game-actions" hidden><button data-ci="unplace">Unplace selected</button><button data-ci="deduce">Use deductions</button><button data-ci="check" class="ci-primary">Check map</button><button data-ci="clear">Clear placements</button><button data-ci="new-game">Restart game</button></div>
        <div data-ci="layers-panel" class="ci-layers-panel" hidden><div class="ci-heading"><h3>Matching distance layers</h3><span>Lines = recovered edges</span></div><svg data-ci="layer-map" viewBox="0 0 700 220" aria-label="Station groups by distance and recovered matches"></svg></div>
        <div class="ci-stats" data-ci="stats"></div>
      </section><aside class="ci-side"><section data-ci="ask-panel" hidden><h3 class="ci-subhead">Ask the distance</h3><div class="ci-query-mode" role="radiogroup" aria-label="Query mode"><label><input data-ci="single-mode" type="radio" name="ci-query-mode" checked> One pair</label><label><input data-ci="batch-mode" type="radio" name="ci-query-mode"> Batch from one station</label></div><div class="ci-ask"><label>From<select data-ci="a"></select></label><label data-ci="single-to">To<select data-ci="b"></select></label><div data-ci="batch-to" class="ci-batch-targets" hidden></div><button data-ci="ask" class="ci-primary">Ask</button></div></section>
        <div class="ci-query" data-ci="query"></div><h3 class="ci-subhead" data-ci="pool-title">Station IDs</h3><div data-ci="pool" class="ci-pool"></div><p class="ci-selection" data-ci="selection"></p>
        <div class="ci-distance-heading"><h3 class="ci-subhead" data-ci="distance-title">Distance groups</h3><button data-ci="pin-distance" type="button" hidden>Pin</button></div><div class="ci-distances" data-ci="distances"></div><div class="ci-pinned-distances" data-ci="pinned-distances" hidden></div>
        <div class="ci-heading ci-history-heading"><h3>Query history</h3><span>Repeated pairs are free</span></div><div class="ci-history" data-ci="history"></div>
      </aside></div><details class="ci-notes"><summary>How to read this lesson</summary><p data-ci="notes"></p></details>`;
    const q=name=>root.querySelector(`[data-ci="${name}"]`),abort=new AbortController(),on=(el,type,fn)=>el.addEventListener(type,fn,{signal:abort.signal});
    let net=M.network(6,19,true),mode=initial,anchor=10,seed=19,trace,cursor=0,timer=null,disposed=false,mask=0,zoom=1,selected=null;
    let game={board:[],queries:[],query:null,batch:null,solved:false},notice='',batchMode=false,batchTargets=new Set(),pinnedSources=new Set(),dragState=null,suppressMapClick=false;
    const ids=()=>Array.from({length:net.size},(_,i)=>i+1);
    const budget=()=>q('budget').value==='practice'?Infinity:4*net.n+6;
    function stop(){clearTimeout(timer);timer=null;q('play').textContent='▶ Play';}
    function syncCase(){const slot=net.slot(anchor);q('case').value=slot===0?'center':slot===net.n/2||slot===net.n-1+net.n/2?'opposite':'ordinary';}
    function controls(){for(const name of ['anchor','a','b']){const old=q(name).value;q(name).replaceChildren();ids().forEach(id=>{const option=document.createElement('option');option.value=id;option.textContent=id;q(name).append(option);});if(Number(old)<=net.size&&Number(old)>0)q(name).value=old;}q('anchor').value=anchor;q('a').value=anchor;q('b').value=anchor===1?2:1;syncCase();}
    function reset(){stop();cursor=0;selected=null;mask=0;zoom=1;notice='';batchMode=false;batchTargets.clear();pinnedSources.clear();if(mode==='game')game={board:Array(net.size).fill(null),queries:[],query:null,batch:null,solved:false};else trace=M.lesson(net,mode,anchor);render();}
    function switchMode(next){mode=next;for(const name of ['center','layers','arms','full','game'])q(name).setAttribute('aria-selected',String(name===mode));const playing=mode==='game';q('playback').hidden=playing;q('budget-label').hidden=!playing;q('ask-panel').hidden=!playing;q('game-actions').hidden=!playing;q('case-label').hidden=!['full','center'].includes(mode);q('anchor-label').hidden=playing||['layers','arms'].includes(mode);q('layers-panel').hidden=mode!=='layers';q('pin-distance').hidden=!playing;
      for(const name of ['pool-title','pool','selection']){(playing?q('game-pool'):q('lesson-pool')).append(q(name));}
      q('intro').textContent={center:'Measure from an anchor. Find the furthest station, then narrow down the center.',layers:'Adjacent layers differ by one. Match edges, then assemble the two circles.',arms:'Use the center’s neighbors to identify each station’s arm.',full:'Different anchors reveal different information. Watch all three cases use their query budget.',game:'Drag an ID onto a station, then use single or batch distance queries to recover the map.'}[mode];
      q('notes').textContent={center:'N counts stations on each ring, so the antipode is N/2 steps from the center. A center anchor has maximum distance N/2; otherwise the furthest station is unique. If its distance from the anchor is D, the center is D−N/2 from the anchor. Test the remaining candidates against the furthest station. The initial N=6 book anchor gives the distance profile in the chapter; switch anchor cases to compare the warm-up profiles.',layers:'The center is given for this focused lesson, and only queries from this starting point are counted. Between interior distance layers there is a one-to-one matching. At the final layer, each antipode accepts two edges. Once only one compatible target remains, infer the edge without querying. During matching, the main map remains unlabeled; the layer diagram shows the information actually recovered. Walk the recovered cycles to assign map positions.',arms:'The center is given for this strategy lesson. Find its four neighbors from the distance-1 group and distinguish their rings using an antipode. Choose each ring’s direction freely. For a station at depth d, its own arm’s center-neighbor is d−1 away; the others are d+1 away. Eliminate arms and infer the final possibility. This is a strategy illustration, not a claim that all cases meet the full solution’s query budget.',full:'Three cases follow the PDF: center, antipode, or an ordinary anchor. An ordinary anchor and a verified second-furthest station solve both rings, apart from a constant-sized tie next to the center. An antipode anchor lets us query the two rings separately. For a center anchor, classify each four-station layer into groups of 1, 1 and 2; infer the fourth category and then resolve the remaining pairs with one query each. The distance-1 exception receives explicit extra queries. The counter includes all distinct oracle calls; 4N+6 is a conservative allowance for the constant-sized checks.',game:'IDs and positions are initially unmatched. Drag an ID chip onto a circle, or use the existing click placement to move it. Batch mode asks every checked destination from one chosen source; every new pair still counts against the budget. Pin a distance profile to compare it with another source while you work. Repeated or self queries cost nothing. Use deductions finds the center from a completed anchor scan, or fills positions forced by your current placements and recorded distances. A warning uses only recorded query contradictions, not hidden answers. Check map compares the full set of labeled edges. Reverse either ring, then swap the two colored rings: all eight drawing orientations preserve the same network. Choose unlimited practice if you want to explore without a budget.'}[mode];reset();
    }
    function position(slot){if(!slot)return{x:350,y:165,cx:350};const ring=slot<net.n?0:1,t=slot-ring*(net.n-1),angle=2*Math.PI*t/net.n,cx=ring?490:210;return{x:cx+(ring?-1:1)*140*Math.cos(angle),y:165-140*Math.sin(angle),cx};}
    function drawMap(s){const query=s.query,board=s.board;let svg='<circle class="ci-ring ci-left" cx="210" cy="165" r="140"/><circle class="ci-ring ci-right" cx="490" cy="165" r="140"/>';
      const conflicts=new Set();if(mode==='game')for(const clue of game.queries){const a=board.indexOf(clue.a),b=board.indexOf(clue.b);if(a>=0&&b>=0&&net.distances[a][b]!==clue.d){conflicts.add(clue.a);conflicts.add(clue.b);}}
      for(let slot=0;slot<net.size;slot++){const display=M.orient(net.n,slot,mask),p=position(display),id=board[slot],active=id!==null&&(id===selected||id===query?.a||id===query?.b),label=id??'?';const x=slot===0?p.x+25:p.x+(p.cx-p.x)/140*28,y=slot===0?p.y+6:p.y+(165-p.y)/140*28+6;
        svg+=`<g class="ci-station${id===null?' is-unknown':''}${active?' is-active':''}${conflicts.has(id)?' is-conflict':''}" data-slot="${slot}" role="button" tabindex="${mode==='game'?0:-1}" aria-label="${slot===0?'Center':`${slot<net.n?'Green':'Purple'} ring position ${display-(display<net.n?0:net.n-1)}`}, ${id===null?'unassigned':`ID ${id}`}"><circle class="ci-hit" cx="${p.x}" cy="${p.y}" r="25"/>${slot===0?`<rect x="343" y="147" width="14" height="36" rx="5"/>`:`<circle cx="${p.x}" cy="${p.y}" r="10"/>`}<text class="ci-station-label" x="${x}" y="${y}" text-anchor="middle">${label}</text></g>`;
      }
      q('map').innerHTML=svg;q('map').style.width=`${zoom*100}%`;q('orientation').textContent=`Orientation ${mask+1} / 8`;
      q('flip-left').setAttribute('aria-pressed',String(Boolean(mask&1)));q('flip-right').setAttribute('aria-pressed',String(Boolean(mask&2)));q('swap-rings').setAttribute('aria-pressed',String(Boolean(mask&4)));
      return conflicts;
    }
    function drawLayers(s){if(mode!=='layers')return;const profile=new Map(s.queries.filter(e=>e.a===s.center||e.b===s.center).map(e=>[e.a===s.center?e.b:e.a,e.d]));profile.set(s.center,0);const groups=Array.from({length:net.n/2+1},(_,d)=>[...profile].filter(([,v])=>v===d).map(([id])=>id)),points=new Map();let svg='';groups.forEach((group,d)=>{const x=40+d*620/(groups.length-1);svg+=`<text x="${x}" y="20" text-anchor="middle" class="ci-layer-label">d = ${d}</text>`;group.forEach((id,i)=>points.set(id,{x,y:60+i*42}));});
      for(const[a,b]of s.edges){const u=points.get(a),v=points.get(b);if(u&&v)svg+=`<path class="ci-matched-edge" d="M${u.x},${u.y}L${v.x},${v.y}"/>`;}
      if(s.query){const a=points.get(s.query.a),b=points.get(s.query.b);if(a&&b)svg+=`<path class="ci-probe-edge${s.query.d===1?' is-edge':''}" d="M${a.x},${a.y}L${b.x},${b.y}"/>`;}
      for(const[id,p]of points)svg+=`<circle class="ci-layer-node" cx="${p.x}" cy="${p.y}" r="13"/><text class="ci-layer-id" x="${p.x}" y="${p.y+5}" text-anchor="middle">${id}</text>`;
      q('layer-map').innerHTML=svg;
    }
    function distanceGroups(source,queries){const distances=new Map([[source,0]]);for(const clue of queries)if(clue.a===source||clue.b===source)distances.set(clue.a===source?clue.b:clue.a,clue.d);const grouped=new Map();for(const[id,d]of distances){if(!grouped.has(d))grouped.set(d,[]);grouped.get(d).push(id);}return{distances,grouped};}
    function drawDistanceGroups(node,source,queries){const {grouped}=distanceGroups(source,queries);node.replaceChildren();[...grouped].sort((a,b)=>a[0]-b[0]).forEach(([distance,labels])=>{const row=document.createElement('div'),label=document.createElement('strong'),stations=document.createElement('span');label.textContent=`d=${distance}`;labels.sort((a,b)=>a-b).forEach(id=>{const station=document.createElement('i');station.textContent=id;stations.append(station);});row.append(label,stations);node.append(row);});return distanceGroups(source,queries).distances.size;}
    function drawBatchTargets(){const host=q('batch-to'),source=Number(q('a').value);host.hidden=!batchMode;q('single-to').hidden=batchMode;host.replaceChildren();if(!batchMode)return;batchTargets.delete(source);const targets=ids().filter(id=>id!==source),all=document.createElement('label'),allBox=document.createElement('input'),allText=document.createElement('span');all.className='ci-batch-all';allBox.type='checkbox';allBox.dataset.batchAll='';allBox.checked=targets.every(id=>batchTargets.has(id));allText.textContent='Select all';all.append(allBox,allText);host.append(all);targets.forEach(id=>{const label=document.createElement('label'),box=document.createElement('input'),text=document.createElement('span');box.type='checkbox';box.value=id;box.checked=batchTargets.has(id);text.textContent=id;label.append(box,text);host.append(label);});}
    function drawPinnedDistances(queries){const host=q('pinned-distances');host.replaceChildren();host.hidden=mode!=='game'||!pinnedSources.size;if(host.hidden)return;pinnedSources.forEach(source=>{const card=document.createElement('section'),heading=document.createElement('header'),title=document.createElement('strong'),remove=document.createElement('button'),groups=document.createElement('div');card.className='ci-pinned-card';title.textContent=`Pinned · from ${source}`;remove.type='button';remove.dataset.unpin=source;remove.textContent='Unpin';groups.className='ci-distances';drawDistanceGroups(groups,source,queries);heading.append(title,remove);card.append(heading,groups);host.append(card);});}
    function render(){const playing=mode==='game',s=playing?game:trace.events[cursor],queries=s.queries,board=s.board,matched=board.filter(id=>id!==null).length;
      const conflicts=drawMap(s);drawLayers(s);q('matched').textContent=`${matched} / ${net.size} IDs placed`;
      q('status').textContent=playing?(notice||(conflicts.size?`Your placements contradict a recorded distance involving ${[...conflicts].join(', ')}. Revise the red stations.`:game.solved?'Recovered the entire network. This orientation is equivalent.':selected===null?'Choose two IDs to query, or select an ID below to place it on the map.':`Selected ID ${selected}. Tap a station to place it.`)):s.note;
      root.dataset.mode=mode;root.dataset.finished=String(playing?game.solved:s.done);q('status').classList.toggle('is-warning',playing&&conflicts.size>0);
      q('single-mode').checked=!batchMode;q('batch-mode').checked=batchMode;
      const last=s.query||queries.at(-1);q('query').innerHTML=playing&&batchMode&&game.batch?.from===Number(q('a').value)?`<small>Batch distances from ${game.batch.from}</small><div class="ci-batch-results">${game.batch.results.map(result=>`<span>${result.to}<i>→</i><strong>${result.d}</strong></span>`).join('')}</div>`:last?`<small>${last.d===null?'Querying':'Last distance'}</small><div><span>${last.a}</span><i>↔</i><span>${last.b}</span><strong>${last.d===null?'…':last.d}</strong></div>`:'<small>No distance queried yet</small><p>What is the shortest path between two station IDs?</p>';
      q('pool-title').textContent=playing?'Select an ID to place':'Recovered and unmatched IDs';
      q('pool').innerHTML=ids().map(id=>`<button data-id="${id}" class="${board.includes(id)?'is-placed':''}${selected===id?' is-selected':''}${s.candidates?.includes(id)?' is-candidate':''}${!playing&&(s.query?.a===id||s.query?.b===id)?' is-query':''}" ${playing?'':'disabled'} aria-label="ID ${id}${board.includes(id)?', placed':', unmatched'}" aria-pressed="${selected===id}">${id}<small>${board.includes(id)?'✓':'?'}</small></button>`).join('');
      q('selection').textContent=playing?'Drag an ID to a station; drag a placed ID away from the map to unassign it.':s.phase;
      const source=playing?Number(q('a').value):(s.reference??s.anchor),known=drawDistanceGroups(q('distances'),source,queries);
      q('distance-title').textContent=`Distances from ${source} · ${known}/${net.size} known`;
      q('pin-distance').textContent=pinnedSources.has(source)?`Unpin ${source}`:`Pin ${source}`;
      drawBatchTargets();drawPinnedDistances(queries);
      q('history').innerHTML=queries.map((e,i)=>`<div class="${i===queries.length-1?'is-current':''}"><small>${i+1}</small> ${e.a} ↔ ${e.b}<strong>${e.d}</strong></div>`).join('');q('history').scrollTop=q('history').scrollHeight;
      const allowance=playing?budget():mode==='full'?4*net.n+6:null;
      q('stats').innerHTML=`<div><strong>${queries.length}${allowance!==null&&Number.isFinite(allowance)?`<small> / ${allowance}</small>`:''}</strong><span>Distinct queries</span></div><div><strong>${matched}</strong><span>${playing?'Your placements':'Recovered IDs'}</span></div><p>${playing?Number.isFinite(allowance)?`Budget: 4N + 6 = ${allowance}`:'Unlimited practice':mode==='full'?`Case: ${s.case??'not classified yet'} · allowance 4N + 6`:['layers','arms'].includes(mode)?'Focused lesson: starts from a known center':'Finding the center only'}</p>`;
      if(!playing){q('progress').textContent=`${cursor+1} / ${trace.events.length}`;q('back').disabled=cursor===0;q('step').disabled=q('play').disabled=q('finish').disabled=cursor===trace.events.length-1;}
      else{const a=Number(q('a').value),b=Number(q('b').value),targets=batchMode?[...batchTargets]:[b],newQueries=targets.filter(to=>to!==a&&!queries.some(entry=>key(entry.a,entry.b)===key(a,to))).length;q('ask').textContent=batchMode?`Ask ${targets.length||'…'}`:'Ask';q('ask').disabled=game.solved||!targets.length||queries.length+newQueries>budget();q('check').disabled=matched!==net.size||game.solved;q('unplace').disabled=selected===null;}
    }
    function step(){if(disposed||mode==='game')return;if(cursor<trace.events.length-1)cursor++;render();if(q('step').disabled)stop();}
    function tick(){step();if(!q('step').disabled&&!disposed)timer=setTimeout(tick,Number(q('speed').value));}
    function rebuild(){const n=Number(q('n').value),book=q('example').value==='book'&&n===6;net=M.network(n,seed,book);anchor=book?10:net.labels[1];controls();reset();}
    for(const name of ['center','layers','arms','full','game'])on(q(name),'click',()=>switchMode(name));
    on(q('n'),'change',()=>{q('example').value='random';rebuild();});on(q('example'),'change',()=>{if(q('example').value==='book')q('n').value=6;rebuild();});on(q('shuffle'),'click',()=>{seed++;q('example').value='random';rebuild();});
    on(q('anchor'),'change',()=>{anchor=Number(q('anchor').value);syncCase();reset();});on(q('case'),'change',()=>{anchor=net.labels[q('case').value==='center'?0:q('case').value==='opposite'?net.n/2:1];q('anchor').value=anchor;reset();});
    on(q('reset'),'click',reset);on(q('step'),'click',()=>{stop();step();});on(q('back'),'click',()=>{stop();cursor=Math.max(0,cursor-1);render();});on(q('play'),'click',()=>{if(timer!==null)stop();else{q('play').textContent='Ⅱ Pause';tick();}});on(q('finish'),'click',()=>{stop();cursor=trace.events.length-1;render();});
    for(const[name,bit]of [['flip-left',1],['flip-right',2],['swap-rings',4]])on(q(name),'click',()=>{mask^=bit;render();});on(q('map-in'),'click',()=>{zoom=Math.min(2,zoom+.25);render();});on(q('map-out'),'click',()=>{zoom=Math.max(1,zoom-.25);render();});
    function startPointerDrag(event,id,originSlot,capture){if(mode!=='game'||game.solved||event.button!==0)return;dragState={pointerId:event.pointerId,id,originSlot,x:event.clientX,y:event.clientY,moved:false,capture};capture.setPointerCapture?.(event.pointerId);}
    function stopPointerDrag(event,cancelled=false){if(!dragState||event.pointerId!==dragState.pointerId)return;const current=dragState;dragState=null;current.capture.releasePointerCapture?.(event.pointerId);root.classList.remove('is-dragging');if(cancelled||!current.moved)return;const station=document.elementFromPoint(event.clientX,event.clientY)?.closest?.('[data-slot]');if(station){selected=current.id;place(Number(station.dataset.slot));}else if(current.originSlot>=0){game.board[current.originSlot]=null;selected=null;notice=`ID ${current.id} returned to the unassigned pool.`;render();}suppressMapClick=true;window.setTimeout(()=>{suppressMapClick=false;},0);}
    on(q('pool'),'click',e=>{const button=e.target.closest('[data-id]');if(mode==='game'&&button){selected=Number(button.dataset.id);notice='';render();}});
    on(q('pool'),'pointerdown',e=>{const button=e.target.closest('[data-id]');if(button)startPointerDrag(e,Number(button.dataset.id),game.board.indexOf(Number(button.dataset.id)),q('pool'));});
    function place(slot){if(mode!=='game'||game.solved)return;notice='';if(selected===null){selected=game.board[slot];render();return;}const previous=game.board.indexOf(selected),replaced=game.board[slot];if(previous>=0)game.board[previous]=replaced;game.board[slot]=selected;selected=null;render();}
    on(q('map'),'click',e=>{if(suppressMapClick){suppressMapClick=false;return;}const station=e.target.closest('[data-slot]');if(station)place(Number(station.dataset.slot));});on(q('map'),'keydown',e=>{if(e.key==='Enter'||e.key===' '){const station=e.target.closest('[data-slot]');if(station){e.preventDefault();place(Number(station.dataset.slot));}}});
    on(q('map'),'pointerdown',e=>{const station=e.target.closest('[data-slot]'),slot=station&&Number(station.dataset.slot),id=Number.isInteger(slot)&&game.board[slot];if(id!==null&&id!==undefined)startPointerDrag(e,id,slot,q('map'));});
    on(document,'pointermove',e=>{if(!dragState||e.pointerId!==dragState.pointerId)return;if(!dragState.moved&&Math.hypot(e.clientX-dragState.x,e.clientY-dragState.y)>7){dragState.moved=true;root.classList.add('is-dragging');}if(dragState.moved)e.preventDefault();});
    on(document,'pointerup',e=>stopPointerDrag(e));on(document,'pointercancel',e=>stopPointerDrag(e,true));
    on(q('unplace'),'click',()=>{const slot=game.board.indexOf(selected);if(slot>=0)game.board[slot]=null;selected=null;game.solved=false;notice='';render();});
    on(q('clear'),'click',()=>{game.board.fill(null);game.solved=false;selected=null;notice='Placements cleared. Your query history is kept.';render();});on(q('new-game'),'click',reset);
    on(q('a'),'change',()=>{batchTargets.clear();game.batch=null;render();});for(const name of ['b','budget'])on(q(name),'change',render);
    on(q('single-mode'),'change',()=>{batchMode=false;render();});on(q('batch-mode'),'change',()=>{batchMode=true;render();});
    on(q('batch-to'),'change',e=>{const box=e.target.closest('input[type=checkbox]');if(!box)return;const source=Number(q('a').value);if(box.hasAttribute('data-batch-all')){batchTargets.clear();if(box.checked)ids().filter(id=>id!==source).forEach(id=>batchTargets.add(id));}else{const id=Number(box.value);if(box.checked)batchTargets.add(id);else batchTargets.delete(id);}render();});
    on(q('pin-distance'),'click',()=>{const source=Number(q('a').value);if(pinnedSources.has(source))pinnedSources.delete(source);else pinnedSources.add(source);render();});
    on(q('pinned-distances'),'click',e=>{const button=e.target.closest('[data-unpin]');if(button){pinnedSources.delete(Number(button.dataset.unpin));render();}});
    on(q('ask'),'click',()=>{const a=Number(q('a').value),targets=batchMode?[...batchTargets]:[Number(q('b').value)],newQueries=targets.filter(b=>b!==a&&!game.queries.some(entry=>key(entry.a,entry.b)===key(a,b)));if(game.queries.length+newQueries.length>budget())return;const results=targets.map(b=>{const existing=game.queries.find(entry=>key(entry.a,entry.b)===key(a,b)),d=existing?.d??net.distance(a,b);if(!existing&&a!==b)game.queries.push({a,b,d});return{to:b,d,free:!!existing||a===b};});game.query=results.length?{a,b:results.at(-1).to,d:results.at(-1).d}:null;game.batch=batchMode?{from:a,results}:null;notice=batchMode?`Measured ${results.length} selected destination${results.length===1?'':'s'} from ${a}.`:`d(${a}, ${results[0].to}) = ${results[0].d}${results[0].free?' · no additional query charged':''}.`;render();});
    on(q('deduce'),'click',()=>{notice='';let count=0;
      if(game.queries.some(e=>{const a=game.board.indexOf(e.a),b=game.board.indexOf(e.b);return a>=0&&b>=0&&net.distances[a][b]!==e.d;})){notice='Revise the red stations first: their placements contradict a recorded distance.';render();return;}
      if(game.board[0]===null){for(const a of ids()){const profile=new Map([[a,0]]);for(const e of game.queries)if(e.a===a||e.b===a)profile.set(e.a===a?e.b:e.a,e.d);if(profile.size!==net.size)continue;const max=Math.max(...profile.values());let center=max===net.n/2?a:null;if(center===null){const far=[...profile].find(([,d])=>d===max)[0],candidates=[...profile].filter(([,d])=>d===max-net.n/2).map(([id])=>id);center=candidates.length===1?candidates[0]:candidates.find(id=>game.queries.some(e=>key(e.a,e.b)===key(far,id)&&e.d===net.n/2));}if(center!==null&&center!==undefined){const old=game.board.indexOf(center);if(old>=0)game.board[old]=null;game.board[0]=center;count++;break;}}}
      let changed=true;while(changed){changed=false;const d=M.domains(net,game.board,game.queries),forced=[...d].find(([,slots])=>slots.length===1);if([...d.values()].some(slots=>!slots.length))break;if(forced){game.board[forced[1][0]]=forced[0];count++;changed=true;}}
      notice=count?`Filled ${count} positions using your current placements and recorded distances.`:'No forced placement yet. A full scan from one ID helps locate the center; then use a second reference to split the distance groups.';render();});
    on(q('check'),'click',()=>{game.solved=M.equivalent(net,game.board);notice=game.solved?'Correct! This map has exactly the hidden network’s connections. All eight drawing orientations are accepted.':'This is not an equivalent map yet. Use more distance clues or revise your placements.';render();});
    controls();if(initial==='game'){q('example').value='random';net=M.network(6,seed);anchor=net.labels[1];controls();}switchMode(initial);
    return()=>{disposed=true;stop();abort.abort();dialog?.classList.remove('ci-dialog');root.remove();};
  }
  window.JournalWidgets=window.JournalWidgets||[];
  window.JournalWidgets.push({id:'center-of-infinity',title:'Center of Infinity',pages:[104,105,106,107,108,109,110,111],badge:{page:105,y:.38},mount:c=>mount(c,'center')});
  window.JournalWidgets.push({id:'infinity-reconstruction',title:'Center of Infinity · Reconstruction',pages:[106,107,108,109,110,111],badge:{page:109,y:.55},mount:c=>mount(c,'full')});
  window.JournalWidgets.push({id:'infinity-game',title:'Center of Infinity · Map Detective',pages:[104,105,106,107,108,109,110,111],badge:{page:104,y:.43},mount:c=>mount(c,'game')});
})();
